PMM-3109 Clickhouse PoC data loader
Percona-Lab/slowlog2clickhouse pull request #1
Opened 2018-11-20 09:18 UTC by askomorokhov

2018-11-20 09:47 UTC, AlekSi reviewed
Should `logs/` directory be committed? If yes, please remove it from `Makefile`.

2018-11-20 09:55 UTC, AlekSi requested changes

2018-11-20 09:55 UTC, AlekSi commented on main.go
> +	if err := tx.Commit(); err != nil {
That kills performance. Please do `stmt.Exec(q)` with different q in a loop with N iterations. N is about 100'000 and should be a flag.

2018-11-20 09:55 UTC, AlekSi commented on main.go
> +		if e := stmt.Close(); e != nil {
The statement should be closed before tthe ransaction is committed:
* begin transaction;
* prepare statement;
* execute statement X times;
* release statement;
* commit transaction.

2018-11-20 09:58 UTC, AlekSi commented on main.go
> +	dsn := flag.String("dsn", "clickhouse://127.0.0.1:9000?database=pmm&x-multi-statement=true", "DSN of ClickHouse Server")
What is `x-multi-statement`?

2018-12-10 14:47 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/Percona-Lab/slowlog2clickhouse?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/Percona-Lab/slowlog2clickhouse?pullRequest=1) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: askomorokhov<br/>:x: AlekSi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/Percona-Lab/slowlog2clickhouse?pullRequest=1) it.</sub>

2018-12-11 12:58 UTC, AlekSi approved these changes

2018-12-11 12:58 UTC, AlekSi commented on README.md
> +Required [Go](https://golang.org/doc/install) and [dep](https://github.com/golang/dep) to build on local machine.
`dep` is not really required.

2018-12-11 12:58 UTC, AlekSi commented on README.md
> +`make build`
Or just `go get github.com/Percona-Lab/slowlog2clickhouse`

2018-12-11 12:58 UTC, AlekSi commented on README.md
> +```
It is not up-to-date. Maybe just drop it.

2018-12-11 12:59 UTC, merged